from typing import Protocol
from bot.packages.i_classes.i_logger import ILogger

class IDocumentProccesor(Protocol):
    def __init__(self, logger: ILogger) -> None: ...
    def convert_pdf_to_document(self, pdf_path): ...
    def process_pdf_documents(self, pdf_dir): ...