from typing import Protocol

class ILogger(Protocol):
    def info(self, msg: str): ...
    def error(self, msg: str): ...
    def warning(self, msg: str): ...
    def critical(self, msg: str): ...
    def debug(self, msg: str): ...
    def get_logger(self): ...