from typing import Protocol
from packages.i_classes.i_logger import ILogger

class IVEctorDB(Protocol):
    def __init__(self, logger: ILogger) -> None: ...
    def connect_db(self, db_path : str): ...
    def create_table(self, db_connection, table_name : str): ...
    def fill_table(self, chunks): ...
    def search_in_table(query_text : str, table, limit : int): ...
    def display_search_results(results): ...
    def interactive_search(db_path=None, table_name=None): ...
    def create_embedding(self, text : str): ...